let car = 'subaru'

console.log("Is car == 'subaru'? | predict True.")
console.log(car == 'subaru')
console.log("Is car != 'subaru'? | predic False")
console.log(car != 'subaru')
console.log("Is car != 'Audi' | predict True")
console.log(car != 'Audi')
console.log("Is car == 'Audi'? | predict False.")
console.log(car == 'Audi')
console.log("Is car != 'BMW'? | predict True.")
console.log(car != 'BMW')
console.log("Is car == 'BMW'? | predict False")
console.log(car == 'BMW')
console.log("Is car != 'Honda'? | predict True")
console.log(car != 'Honda')
console.log("Is car == 'Honda' ? | predict False")
console.log(car == 'Honda')
console.log("Is car != 'Toyota' ? | predict True")
console.log(car != 'Toyota')
console.log("Is car == 'Toyota'? | predict False")
console.log(car == 'Toyota')